
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: django_backend
    command: ./docker/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: